from enum import IntEnum

TIE = 0
BLACK_WIN = 1
WHITE_WIN = -1
NOT_SURE = 2

MACHINE_MACHINE = 0
MACHINE_HUMAN = 1
HUMAN_MACHINE = -1

HARD = 1
NORMAL = 0
EASY = -1

MACHINE = 1
HUMAN = 0
OPPONENT_MACHINE = -1

KIND_1 = 1
KIND_2 = 2

WIDTH = 15
HEIGHT = 15
BLACK = 1
WHITE = -1
BLANK = 0
DEPTH = 4

REC_SIZE = 50
CHESS_RADIUS = REC_SIZE // 2 - 2
CHESS_LEN = 15
MAP_WIDTH = CHESS_LEN * REC_SIZE
MAP_HEIGHT = CHESS_LEN * REC_SIZE

INFO_WIDTH = 200
BUTTON_WIDTH = 140
BUTTON_HEIGHT = 50

SCREEN_WIDTH = MAP_WIDTH + INFO_WIDTH
SCREEN_HEIGHT = MAP_HEIGHT

SCORE_MAX = 0x7fffffff
SCORE_MIN = -1 * SCORE_MAX
SCORE_FIVE = 10000


class MAP_ENTRY_TYPE(IntEnum):
    MAP_EMPTY = 0,
    MAP_PLAYER_ONE = 1,
    MAP_PLAYER_TWO = 2,
    MAP_NONE = 3,


class CHESS_TYPE(IntEnum):
    NONE = 0,
    SLEEP_TWO = 1,
    LIVE_TWO = 2,
    SLEEP_THREE = 3
    LIVE_THREE = 4,
    CHONG_FOUR = 5,
    LIVE_FOUR = 6,
    LIVE_FIVE = 7,
